### ISSUE TITLE
Error using spsa related to float/integer conversion

### ISSUE THREAD

**Issue by Matthies** [fsmosca/Lakas#8]
With latest changes I'm getting the following error when using spsa optimizer:
```
python -u lakas.py --optimizer spsa --input-data-file bay_nodes100000.dat --output-data-file bay_nodes100000.dat --optimizer-log-file log_bay-nodes100000.txt --nodes 100000 --base-time-sec 10 --inc-time-sec 1 --budget 5 --games-per-budget 500 --concurrency 14 --engine ./engines/RubiChess-AVX2.exe --input-param "{'NnueOutBias': {'init':-1613, 'lower':-1800, 'upper':-1400}, 'NnueOutWeight_00': {'init':-17, 'lower':-97, 'upper':63}, 'NnueOutWeight_01': {'init':-14, 'lower':-94, 'upper':66}, 'NnueOutWeight_02': {'init':23, 'lower':-57, 'upper':103}, 'NnueOutWeight_03': {'init':-87, 'lower':-128, 'upper':-7}, 'NnueOutWeight_04': {'init':4, 'lower':-76, 'upper':84}, 'NnueOutWeight_05': {'init':-44, 'lower':-124, 'upper':36}, 'NnueOutWeight_06': {'init':40, 'lower':-40, 'upper':120}, 'NnueOutWeight_07': {'init':-77, 'lower':-128, 'upper':3}, 'NnueOutWeight_08': {'init':89, 'lower':9, 'upper':127}, 'NnueOutWeight_09': {'init':10, 'lower':-70, 'upper':90}, 'NnueOutWeight_10': {'init':-32, 'lower':-112, 'upper':48}, 'NnueOutWeight_11': {'init':66, 'lower':-14, 'upper':127}, 'NnueOutWeight_12': {'init':-22, 'lower':-102, 'upper':58}, 'NnueOutWeight_13': {'init':-8, 'lower':-88, 'upper':72}, 'NnueOutWeight_14': {'init':-115, 'lower':-128, 'upper':-35}, 'NnueOutWeight_15': {'init':50, 'lower':-30, 'upper':127}, 'NnueOutWeight_16': {'init':-32, 'lower':-112, 'upper':48}, 'NnueOutWeight_17': {'init':-19, 'lower':-99, 'upper':61}, 'NnueOutWeight_18': {'init':-51, 'lower':-128, 'upper':29}, 'NnueOutWeight_19': {'init':-16, 'lower':-96, 'upper':64}, 'NnueOutWeight_20': {'init':127, 'lower':47, 'upper':127}, 'NnueOutWeight_21': {'init':51, 'lower':-29, 'upper':127}, 'NnueOutWeight_22': {'init':-19, 'lower':-99, 'upper':61}, 'NnueOutWeight_23': {'init':19, 'lower':-61, 'upper':99}, 'NnueOutWeight_24': {'init':-23, 'lower':-103, 'upper':57}, 'NnueOutWeight_25': {'init':-16, 'lower':-96, 'upper':64}, 'NnueOutWeight_26': {'init':92, 'lower':12, 'upper':127}, 'NnueOutWeight_27': {'init':-26, 'lower':-106, 'upper':54}, 'NnueOutWeight_28': {'init':20, 'lower':-60, 'upper':100}, 'NnueOutWeight_29': {'init':-9, 'lower':-89, 'upper':71}, 'NnueOutWeight_30': {'init':-11, 'lower':-91, 'upper':69}, 'NnueOutWeight_31': {'init':-10, 'lower':-90, 'upper':70}}" --opening-file ./start_opening/noob_3moves.epd --opening-file-format epd
```
```
python : Traceback (most recent call last):
In Zeile:1 Zeichen:1
+ python -u lakas.py --optimizer spsa --input-data-file spsa80_nodes100 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "lakas.py", line 905, in <module>
    main()
  File "lakas.py", line 867, in main
    loss = objective.run(**x.kwargs)
  File "C:\Schach\game_param_tuner\Lakas-main\myvenv\lib\site-packages\nevergrad\parametrization\container.py", line 89, in kwargs
    return self[1].value  # type: ignore
  File "C:\Schach\game_param_tuner\Lakas-main\myvenv\lib\site-packages\nevergrad\parametrization\core.py", line 555, in value
    return {k: as_parameter(p).value for k, p in self._content.items()}
  File "C:\Schach\game_param_tuner\Lakas-main\myvenv\lib\site-packages\nevergrad\parametrization\core.py", line 555, in <dictcomp>
    return {k: as_parameter(p).value for k, p in self._content.items()}
  File "C:\Schach\game_param_tuner\Lakas-main\myvenv\lib\site-packages\nevergrad\parametrization\data.py", line 503, in value
    return float(self._value[0]) if not self.integer else int(np.round(self._value[0]))
ValueError: cannot convert float NaN to integer
```

Maybe related to a844798dafcd920dbef29d187f989861f4ef8c43

**Comment by fsmosca** [comment]
The error came from initializing the loss of spsa before the optimization even started. Normally before the optimization begins I initialize the optimizer with 0.5 value for init param. But spsa is different as it will attempt to call the objective function twice one negative perturbation and the other is positive perturbation, after that it can then tell which param values to try. 

The fix is not to initialize the optimizer for spsa to avoid the error, just let it run to record its optimization data on its own. No external data input is applied in the beginning of optimization.
